### PR TITLE
Add setup.py

### PR DESCRIPTION
**Pull request by mmterpstra**
Although completely optional / not required you could add and expand a setup.py and a requirements.txt for easy installation. You could also consider to add testing using for example travis and codecov.

This is more as a learning opportunity than a actual need for this projects though.

this setup.py was created using the gsport and coloredlogs github python projects as an example

edited in pycharm community edition

### CODE REVIEW

**Comment by mmterpstra** [comment]
Also consider to restricting the library versions for more reproducible installations.

**Review by KyranWissink — APPROVED** [review]
Very helpful and thank you very much!

**Comment by mmterpstra** [comment]
here is an intro for writing tests in 3 different ways...atlhough I'm nt sure what would be best for your project(s).

https://pythontesting.net/framework/nose/nose-introduction/

**Comment by mmterpstra** [comment]
`pip list| grep 'name\|pandas\|hgvs\|pyfaidx\|pyensemblrest'` for stricter version requirements (please for specifying in the requirements use the >= )
mine gave:
```
hgvs==1.5.1
pandas==1.2.4
pyensemblrest==0.2.3
pyfaidx==0.5.9.5
```

**Pull request merged**
